# Generated by Django 4.0 on 2022-03-12 12:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_source_rename_comment_comment_text_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.AddField(
            model_name='source',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academy.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='pdf',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='script',
            field=models.FileField(blank=True, null=True, upload_to='script/'),
        ),
        migrations.AddField(
            model_name='source',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_image/'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 17, 40, 12, 967082)),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 17, 40, 12, 967082)),
        ),
    ]
