# Generated by Django 4.0 on 2022-03-12 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_delete_feedback_source_course_source_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Image size should be at least 1200x800', null=True, upload_to='course_image/'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 0, 31, 49, 59988)),
        ),
        migrations.AlterField(
            model_name='source',
            name='pdf',
            field=models.URLField(blank=True, help_text='PDF file link', null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='script',
            field=models.FileField(blank=True, help_text='upload script file', null=True, upload_to='script/'),
        ),
        migrations.AlterField(
            model_name='source',
            name='video',
            field=models.URLField(blank=True, help_text='Youtube video link', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 0, 31, 49, 59988)),
        ),
    ]
