# Generated by Django 4.0 on 2022-03-15 12:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_remove_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(help_text='https://www.w3schools.com/icons/fontawesome5_icons_alert.asp  https://fontawesome.ru/cheatsheet/\n\tExapmle: fa fa-code', max_length=25),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 17, 7, 21, 701714)),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 17, 7, 21, 703714)),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=255)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.course')),
            ],
        ),
        migrations.AlterField(
            model_name='source',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.theme'),
        ),
    ]
